### ISSUE TITLE
Alarms: add log metric alarms to CloudQuery and the CSP report service

### ISSUE THREAD

**Issue by patheard** [cds-snc/security-tools#102]
# Summary
Currently there are no alarms or Slack ops channel integrations with the security tools products.  As a result, we're missing cases where the services have problems or have gone down.

## Todo

- [x] CloudWatch metric alarms, defined in Terraform, based on errors in the logs of each service
- [x] New Slack channel and webhook to post alarm status when errors are detected.

**Comment by CalvinRodo** [comment]
Due to crashes caused by neo4j versions we really need to increase the priority on this.

**Comment by patheard** [comment]
The CSP report service now has error alarms.

**Comment by patheard** [comment]
CloudQuery also has alert rules based on the Sentinel alerts that are triggered if data is not being properly sent on a daily basis:
https://github.com/cds-snc/sentinel/blob/0ac0e4349708c9eb167ee20688634cbf1174b69c/terraform/alert_rules_sentinel/alert_rule_sentinel_connectors.tf
