### ISSUE TITLE
Setup Cloudquery to scan all accounts

### ISSUE THREAD

**Issue by CalvinRodo** [cds-snc/security-tools#242]
- [x] Terraform for Cloudquery and new Postgresql RDS
- [x] Remove Cartography infrastructure
- [x] Send data to Sentinel

**Comment by CalvinRodo** [comment]
This is blocking the following: 

- https://github.com/cds-snc/security-risk-register/issues/98
- https://github.com/cds-snc/security-risk-register/issues/37
- https://github.com/cds-snc/security-risk-register/issues/47

**Comment by gcharest** [comment]
CloudQuery has been tested locally. [Development branch](https://github.com/cds-snc/security-tools/tree/feat/cloudquery)

**Comment by gcharest** [comment]
Not going to use Postgresql, pushing straight to S3 as Parquet format
