### ISSUE TITLE
Improve how we're downloading the AWS Sentinel Connector lambda layer

### ISSUE THREAD

**Issue by patheard** [cds-snc/security-tools#95]
# Summary
Some Docker image builds in this repo are using the AWS Sentinel Connector lambda layer:
- [Layer download in the workflow](https://github.com/cds-snc/security-tools/blob/40216f2279329b79a97113bbe102b510b59f7a02/.github/workflows/ci_build_containers.yml#L62-L70)
- [Layer source](https://github.com/cds-snc/aws-sentinel-connector-layer)

The issue we're facing is that when a new version of the layer is published, AWS deleted any previous, unused versions.  Since our use in the Docker image is not detected, the referenced layer is deleted, and subsequent builds fail.

# Potential fixes
- Clone the `cds-snc/aws-sentinel-connector-layer` at a specific tag and build the layer code ourselves as part of the docker image build.
- Consume a built artifact or Docker image that's created as part of the `cds-snc/aws-sentinel-connector-layer` workflows.

# Related
- cds-snc/aws-sentinel-connector-layer#7

**Comment by ascheid** [comment]
aws-sentinel-connector now has a docker build step that builds and push the image for it to be consumed by other projects. Security-tools is now consuming this docker image to acquire the required python connector.
